#!/bin/sh
getent group colord || /usr/sbin/groupadd -r colord
getent passwd colord || /usr/sbin/useradd -r -g colord -G colord -d /var/lib/colord -s /sbin/nologin -c "Colord System User" colord
/usr/bin/passwd -l colord > /dev/null
